[rpc_endpoints]
mainnet = "https://api.mainnet-beta.solana.com"
devnet = "https://api.devnet.solana.com"
testnet = "https://api.testnet.solana.com"
localnet = "http://127.0.0.1:8899"
debug = "http://34.90.18.145:8899"
